version: '2'
services:

 flyway-rest-integration:
    container_name: 'flyway-rest-integration'
    build:
      context: ./../../.
      dockerfile: ./docker/flyway-rest-integration/Dockerfile
    environment:
      - FLYWAY_REST_PORT=9001
      - FLYWAY_REST_HOST=flyway-rest
      - NODE_ENV=production
    command: npm run test
