sudo: required
services:
  - docker

cache:
  directories:
    - node_modules

global:
  - DOCKER_VERSION="1.9.1-0~trusty"


env:
  DOCKER_COMPOSE_VERSION: 1.8.0

before_install:
  # Install older version of docker
  - sudo apt-get update
  - sudo apt-get remove docker-engine -yq
  - sudo apt-get install docker-engine=$DOCKER_VERSION -yq --no-install-suggests --no-install-recommends --force-yes -o Dpkg::Options::="--force-confnew"
  # Install docker-compose
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:

script:
  - chmod a+x ./test.sh && ./test.sh

after_script:
