# Potential improvements: # Fixed version of docker: https://github.com/erikdstock/tipjar/blob/master/.travis.yml

sudo: required
services:
  - docker

cache:
  directories:
    - node_modules

env:
  DOCKER_COMPOSE_VERSION: 1.8.0

before_install:
  # Install docker-compose
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:

script:
  - chmod a+x ./docker/docker-ci.sh && ./docker/docker-ci.sh

after_script:

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    Image="$(docker images | grep "flyway-rest" | grep -v grep | awk '{print $3}')";
    echo $Image;
    docker tag $Image stefanwalther/flyway-rest:latest;
    docker push stefanwalther/flyway-rest;
    fi
