version: '2'
services:

  flyway_rest_db:
    extends:
      file: ./flyway_rest_db/docker-compose.yml
      service: flyway_rest_db

  flyway-rest:
    extends:
      file: ./flyway-rest/docker-compose.yml
      service: flyway-rest
    links:
      - flyway_rest_db

  flyway_rest_integration:
    extends:
      file: ./flyway_rest_integration/docker-compose.yml
      service: flyway_rest_integration
    links:
      - flyway-rest
      - flyway_rest_db
