version: '2'
services:

  flyway-rest-db:
    extends:
      file: ./flyway-rest-db/docker-compose.yml
      service: flyway-rest-db

  flyway-rest:
    extends:
      file: ./flyway-rest/docker-compose.yml
      service: flyway-rest
    links:
      - flyway-rest-db
    volumes:
      - ./../:/home/app/
    command: "npm run start:dev"
    environment:
      - NODE_ENV=development

  flyway-pgadmin:
    container_name: "flyway-pgadmin"
    image: fenglc/pgadmin4:1.1
    ports:
      - "5050:5050"
    links:
      - flyway-rest-db

