version: '2'
services:

  flyway-rest:
    container_name: 'flyway-rest'
    build:
      context: ./../../.
      dockerfile: ./docker/flyway-rest/Dockerfile
    environment:
      - PORT=9001doc
      - NODE_ENV=production
    ports:
      - "9001:9001"
    command: "npm run start"
