---
swagger: '2.0'

################################################################################
#                              API Information                                 #
################################################################################
info:
  version: 0.0.2
  title: flyway-rest
  description: REST interface for flyway (http://flywaydb.org)

################################################################################
#                                   Paths                                      #
################################################################################
paths:
  /info:
    get:
      description: |
        Returns the details and status information about all the migrations.

        [Official Documentation](https://flywaydb.org/documentation/commandline/info)
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: Configuration
          description: Configuration object
          required: true
          schema:
            $ref: "#/definitions/configuration"
      responses:
        200:
          description: Result object for 200 OK
          schema:
            $ref: "#/definitions/result"
        500:
          description: Result object for 500 Error
          schema:
            $ref: "#/definitions/errorResult"
  /clean:
    post:
      description: |
        Clean ...
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: Configuration
          description: Configuration object
          required: true
          schema:
            $ref: "#/definitions/configuration"
      responses:
        200:
          description: Result object for 200 OK
          schema:
            $ref: "#/definitions/result"
        500:
          description: Result object for 500 Error
          schema:
            $ref: "#/definitions/errorResult"
  /migrate:
    post:
      description: |
        Clean ...
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: Configuration
          description: Configuration object
          required: true
          schema:
            $ref: "#/definitions/configuration"
      responses:
        200:
          description: Result object for 200 OK
          schema:
            $ref: "#/definitions/result"
        500:
          description: Result object for 500 Error
          schema:
            $ref: "#/definitions/errorResult"
  /repair:
    post:
      description: |
        Clean ...
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: Configuration
          description: Configuration object
          required: true
          schema:
            $ref: "#/definitions/configuration"
      responses:
        200:
          description: Result object for 200 OK
          schema:
            $ref: "#/definitions/result"
        500:
          description: Result object for 500 Error
          schema:
            $ref: "#/definitions/errorResult"
  /validate:
    post:
      description: |
        Clean ...
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: Configuration
          description: Configuration object
          required: true
          schema:
            $ref: "#/definitions/configuration"
      responses:
        200:
          description: Result object for 200 OK
          schema:
            $ref: "#/definitions/result"
        500:
          description: Result object for 500 Error
          schema:
            $ref: "#/definitions/errorResult"

################################################################################
#                                 Definitions                                  #
################################################################################
definitions:
  configuration:
    type: object
    properties:
      mode:
        type: string
        description: the mode
        enum:
          - get-cmd
          - sync
      files:
        description: Files to use for the FlywayDB action.
        type: array
        items:
          $ref: "#/definitions/fileDef"
      flyway_args:
        type: object
        properties:
          test:
            type: string
  fileDef:
    properties:
      name:
        type: string
        description: Name of the file.
      base64:
        type: string
        description: base64 string of the file's content.
  result:
    properties:
      status:
        type: string
        enum:
          - OK
          - Error
          - ValidationError
      action:
        type: string
        enum:
          - clean
          #Todo: Add the other actions here
      mode:
        type: string
        description: The mode of the request.
        enum:
          - get-cmd
          - sync
      cmd:
        type: string
        description: The command to be executed.
      validationErrors:
        type: array
        items:
          $ref: "#/definitions/validationErrors"
  errorResult:
    properties:
      status:
        type: string
        enum:
          - Error
          - ValidationError
      errorMsg:
        type: string
      validationErrors:
        type: array
        items:
          $ref: "#/definitions/validationErrors"
  validationErrors:
    type: array
    items:
      type: string


